spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybtdb?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false
    username: root
    password: fcfa7e6a31fdb635
server:
  port: 80

mybatis:
  mapper-locations: classpath:com.whx.dao/*.xml